version: '2'
services:
    skc-app:
        image: skc
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://skc-postgresql:5432/skc
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    skc-postgresql:
        extends:
            file: postgresql.yml
            service: skc-postgresql
